<?xml version="1.0"?>
<package format="3">
  <name>g1_speech_ros2</name>
  <version>0.1.0</version>
  <description>ROS 2 lifecycle wrapper for G1 Speech Service.</description>
  <maintainer email="howtoliy@gmail.com">Coldmooon</maintainer>
  <license>Unspecified</license>

  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>g1_speech_msgs</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>lifecycle_msgs</exec_depend>
  <exec_depend>rclpy</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
